/* DADASHMODE v3 · UI: control room, inspector, pages, events, boot */
'use strict';
let P=null;
function migrate(p){
  p.format='dadashmode-episode/3';p.id=p.id||uid();p.name=p.name||'قسمت جدید';p.unit=p.unit||'ثانیه';p.startBank=Number.isFinite(+p.startBank)?+p.startBank:20;
  p.layout=Object.assign({score:'bottom',timer:'top',sub:46,green:false,guides:true},p.layout||{});
  p.theme=Object.assign({font:'Lalezar'},THEMES[0],p.theme||{});
  p.speakers=(p.speakers&&p.speakers.length?p.speakers:[{id:'host',name:'مجری',provider:'gemini',voice:'Leda'}]).map(s=>Object.assign({provider:'gemini',voice:'Leda'},s));
  p.players=(p.players&&p.players.length?p.players:defaultEpisode().players).map((x,i)=>Object.assign({id:uid(),symbol:'●',color:PLAYER_COLS[i],key:''},x));
  p.segments=(p.segments||[]).map(s=>mkSeg(s));
  p.segments.forEach(s=>s.lines=(s.lines||[]).map(l=>Object.assign({id:uid(),speaker:p.speakers[0].id,emotion:'warm',text:'',direction:''},l)));
  if(p.autoAdvance===undefined)p.autoAdvance=true;p.game=Object.assign(freshGame(),p.game||{});p.created=p.created||Date.now();return p}
let saveT;function save(){clearTimeout(saveT);saveT=setTimeout(async()=>{P.updated=Date.now();await DB.put('projects',P.id,P);localStorage.setItem('dm3-last',P.id)},300)}
const allLines=()=>P.segments.flatMap((s,si)=>s.lines.map((l,li)=>({s,si,l,li})));
function optList(obj,cur){return Object.entries(obj).map(([k,v])=>`<option value="${k}" ${k===cur?'selected':''}>${esc(typeof v==='string'?v:v.fa)}</option>`).join('')}

/* ---------------- control room ---------------- */
function segHealth(s){if(s.status==='issue'||s.issue)return 'bad';if(s.lines.some(l=>vstat(l)!=='ready')||s.status==='draft')return 'warn';return 'ok'}
function renderROS(){$('#rosCount').textContent=fa(P.segments.length)+' مرحله';$('#ros').innerHTML=P.segments.map((s,i)=>{const ready=s.lines.filter(l=>vstat(l)==='ready').length;
  return `<li class="ros-item ${i===st.sel?'sel':''} ${i===st.live?'live':''}" data-i="${i}"><span class="num">${fa(i+1)}</span><span class="dot ${segHealth(s)}"></span>
  <div class="ros-main"><span class="ros-type">${TYPES[s.type]}${s.game!=='generic'&&['intro','rules','play'].includes(s.type)?' · '+GAMES[s.game]:''}</span><strong>${esc(s.title||'بی‌عنوان')}</strong><span class="ros-meta">${s.lines.length?fa(ready)+'/'+fa(s.lines.length)+' صدا':'بدون دیالوگ'}${s.issue?' · ایراد ثبت شده':''}</span></div>
  <div class="ros-act"><button class="btn sm icon ghost" data-act="cue" title="اجرای زنده"><i data-lucide="play"></i></button><button class="btn sm icon ghost" data-act="up" title="بالا"><i data-lucide="chevron-up"></i></button><button class="btn sm icon ghost" data-act="down" title="پایین"><i data-lucide="chevron-down"></i></button></div></li>`}).join('')||'<li class="empty">هنوز مرحله‌ای نیست. از پایین اضافه کنید یا از «سناریو» بسازید.</li>';icons($('#ros'))}
function renderInspector(){const s=P.segments[st.sel];const el=$('#insp');if(!s){el.innerHTML='<p class="empty">مرحله‌ای انتخاب نشده.</p>';return}
  $('#inspTitle').textContent=`مرحله ${fa(st.sel+1)} · ${TYPES[s.type]}`;
  const spOpts=id=>P.speakers.map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${esc(p.name)}</option>`).join('');
  const showGame=['intro','rules','play'].includes(s.type);
  el.innerHTML=`
  <div class="status-pick" role="group" aria-label="وضعیت">${[['ok','آماده'],['draft','پیش‌نویس'],['issue','نیاز به اصلاح']].map(([v,l])=>`<button data-v="${v}" aria-pressed="${s.status===v}">${l}</button>`).join('')}</div>
  <div class="grid2"><label class="f">نوع مرحله<select data-f="type">${optList(TYPES,s.type)}</select></label>${showGame?`<label class="f">بازی / تصویرسازی<select data-f="game">${optList(GAMES,s.game)}</select></label>`:s.type==='winner'?`<label class="f">برنده (خالی = پیشتاز)<select data-f="winner"><option value="">خودکار</option>${P.players.map(c=>`<option ${c.name===s.winner?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`:'<span></span>'}</div>
  ${s.type==='play'?`<div class="grid2"><label class="f">زمان (ثانیه)<input type="number" min="5" data-f="duration" value="${s.duration}"></label><label class="f">جایزهٔ برد (${esc(P.unit)})<input type="number" data-f="reward" value="${s.reward}"></label></div>`:''}
  <label class="f">عنوان روی صحنه<input type="text" data-f="title" value="${esc(s.title)}"></label>
  <label class="f">${s.type==='card'?'متن کارت':'زیرعنوان'}<input type="text" data-f="subtitle" value="${esc(s.subtitle)}"></label>
  ${s.type==='rules'?`<label class="f">قوانین (هر خط یک قانون)<textarea data-f="rules" rows="${Math.max(3,s.rules.length+1)}">${esc(s.rules.join('\n'))}</textarea><span class="muted">هر قانون با دیالوگ هم‌شماره‌اش ظاهر می‌شود${s.lines.length>s.rules.length?' (دیالوگ اول مقدمه است)':''}.</span></label>`:''}
  <div class="lines-head"><span class="eyebrow">دیالوگ‌ها و لحن${s.type==='play'?' (در بازی زنده دستی پخش می‌شوند)':''}</span><button class="btn sm" data-la="add"><i data-lucide="plus"></i>دیالوگ</button></div>
  <div>${s.lines.map((l,k)=>{const v=vstat(l);return `<div class="line" data-li="${k}" data-id="${l.id}">
    <div class="line-top"><span class="ln-num">${fa(k+1)}</span><select data-lf="speaker" aria-label="گوینده">${spOpts(l.speaker)}</select><select data-lf="emotion" aria-label="لحن">${optList(EMO,l.emotion)}</select><span class="vchip ${v}">${VLABEL[v]}</span></div>
    <textarea data-lf="text" rows="2" aria-label="متن دیالوگ">${esc(l.text)}</textarea>
    <input type="text" data-lf="direction" value="${esc(l.direction)}" placeholder="دستور لحن (اختیاری): آرام شروع کن، آخرش با خنده">
    <div class="line-act"><button class="btn sm" data-la="play"><i data-lucide="volume-2"></i>پخش</button><button class="btn sm" data-la="cue" title="پخش روی آنتن با زیرنویس"><i data-lucide="send"></i>روی آنتن</button><button class="btn sm" data-la="gen"><i data-lucide="sparkles"></i>ساخت صدا</button><button class="btn sm" data-la="mic"><i data-lucide="mic"></i>ضبط خودم</button><label class="btn sm"><i data-lucide="upload"></i>فایل<input type="file" accept="audio/*" data-la="file" hidden></label><button class="btn sm icon ghost" data-la="up" title="بالا"><i data-lucide="chevron-up"></i></button><button class="btn sm icon ghost" data-la="del" title="حذف"><i data-lucide="x"></i></button></div></div>`}).join('')||'<p class="muted">این مرحله دیالوگی ندارد.</p>'}</div>
  <label class="f">ایراد این مرحله (برای اصلاح)<input type="text" data-f="issue" value="${esc(s.issue)}" placeholder="مثلاً: قانون ۳ طولانی است، زیرنویس دو خطی شد"></label>
  <label class="f">یادداشت کارگردان (دوربین، وسایل، افکت)<textarea data-f="notes" rows="3">${esc(s.notes)}</textarea></label>`;icons(el);markSpeaking()}
function renderScores(){$('#scores').innerHTML=P.players.map((p,i)=>`<div class="pbank" data-pi="${i}"><span class="sym" style="background:${p.color}">${esc(p.symbol)}</span><div><div class="nm">${esc(p.name)} <span class="muted">${p.key?'کلید '+p.key.toUpperCase():''}</span></div><div class="val">${fa(bankOf(p.id))} <span class="muted" style="font:700 13px Vazirmatn">${esc(P.unit)}</span></div></div>
  <div class="row" style="gap:4px;flex-wrap:nowrap"><button class="btn sm" data-sc="-">−${fa(S.step)}</button><button class="btn sm pri" data-sc="+">+${fa(S.step)}</button></div></div>`).join('')||'<p class="muted">بازیکنی نیست (تم و چیدمان ← بازیکن‌ها).</p>';
  $$('#stepCtl button').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.step===S.step));renderVarBtn()}
function renderVarBtn(){const b=$('#varBtn');if(!b)return;b.querySelector('span').textContent=G().var?'پایان بازبینی VAR':'بازبینی VAR';b.classList.toggle('pri',G().var);b.classList.toggle('info',!G().var)}
function pBtns(fn,label,cls=''){return `<div class="row">${P.players.map(p=>`<button class="btn player ${cls}" style="border-color:${p.color}" data-g="${fn}" data-p="${p.id}">${esc(p.symbol)} ${label.replace('{n}',esc(p.name))}</button>`).join('')}</div>`}
function renderGameDeck(){const el=$('#gameDeck');if(!el||!P)return;const s=P.segments[curSegIndex()];renderVarBtn();
  if(!s||!['play','rules','intro'].includes(s.type)){el.innerHTML=`<div class="game-box"><h4>کنترل بازی</h4><p class="muted" style="margin:0">یک مرحلهٔ «بازی زنده» را انتخاب یا اجرا کنید تا کنترل‌های مخصوص همان بازی اینجا بیاید. امتیازدهی دستی همیشه از ستون کناری ممکن است.</p></div>`;renderQuickLines();return}
  const g=s.game,R=s.reward;let h=`<div class="game-box"><h4>${esc(GAMES[g])} <span class="muted">· ${esc(s.title)}</span></h4>`;
  if(g==='distance'){h+=P.players.map(p=>{const d=G().distance[p.id]||{};return `<div style="display:grid;gap:6px"><b style="color:${p.color}">${esc(p.symbol+' '+p.name)}</b><div class="row">${Object.entries(DIST).map(([k,v])=>`<button class="btn sm" style="${d.choice===k?'background:'+v.col+';color:#111;border-color:'+v.col:''}" data-g="dlock" data-p="${p.id}" data-v="${k}">${v.fa} +${fa(v.sec)}</button>`).join('')}</div><div class="row"><button class="btn sm ok" data-g="dhit" data-p="${p.id}">✓ گل</button><button class="btn sm" data-g="dmiss" data-p="${p.id}">✕ خطا</button><span class="muted">تلاش ${fa((d.att||[]).length)} از ${fa(distMax(p.id))}</span></div></div>`}).join('')}
  else if(g==='mystery'){const m=G().mystery;h+=`<div class="row"><button class="btn sm" data-g="mnew">توزیع مخفی جدید</button><span class="muted">${m.dist?'توزیع آماده و مخفی است':'هنوز توزیعی ساخته نشده'}</span></div>`;
    h+=P.players.map(p=>`<div style="display:grid;gap:6px"><b style="color:${p.color}">${esc(p.symbol+' '+p.name)}${m.picks[p.id]?' · جعبه '+fa(m.picks[p.id]):''}</b><div class="boxes">${[1,2,3,4,5,6].map(b=>`<button class="${m.picks[p.id]===b?'picked':''} ${m.opened[b]?'opened':''}" data-g="mpick" data-p="${p.id}" data-v="${b}">${fa(b)}</button>`).join('')}</div><button class="btn sm pri" data-g="mreveal" data-p="${p.id}">لقمه خورده شد · افشا</button></div>`).join('')}
  else if(g==='mitts'){h+=pBtns('mitts','برد {n} + کارت خرابکاری','ok');const sb=Object.entries(G().sabotage);if(sb.length)h+=`<p class="muted" style="margin:0">${sb.map(([k,v])=>esc(pl(k)?.name)+': '+esc(v)).join(' · ')}</p>`}
  else if(g==='powers'){h+=P.players.map(p=>{const list=G().powers[p.id]||[];return `<div style="display:grid;gap:6px"><b style="color:${p.color}">${esc(p.symbol+' '+p.name)} · ${fa(bankOf(p.id))}</b><div class="row">${POWERS.map(pw=>`<button class="btn sm" data-g="pbuy" data-p="${p.id}" data-v="${pw.id}" title="${esc(pw.desc)}">${esc(pw.name)}${pw.variable?'':' '+fa(pw.cost)}</button>`).join('')}<input type="number" min="1" placeholder="شرط" data-stake="${p.id}" style="width:80px"></div>
      ${list.map((it,i)=>{const pw=POWERS.find(z=>z.id===it.id);return `<div class="row"><span>🔒 ${esc(pw.name)}${it.stake&&pw.variable?' ('+fa(it.stake)+')':''}</span>${(it.id==='double'||it.id==='allin')&&it.resolved===null?`<button class="btn sm ok" data-g="pres" data-p="${p.id}" data-v="${i}" data-ok="1">موفق</button><button class="btn sm" data-g="pres" data-p="${p.id}" data-v="${i}" data-ok="0">شکست</button>`:it.resolved===null?'':`<span class="muted">${it.resolved?'موفق':'شکست'}</span>`}</div>`}).join('')}</div>`}).join('')+`<p class="muted" style="margin:0">بازگشت ALL IN ${G().comebackUsed?'استفاده شده':'هنوز آزاد'} · فقط نفر عقب‌تر.</p>`}
  else if(g==='vault'){const v=G().vault;h+=`<div class="row"><span class="eyebrow">رمزها (فقط کارگردان)</span><div class="codes">${(v.codes.length?v.codes:['؟','؟','؟']).map(c=>`<span>${fa(c)}</span>`).join('')}</div><button class="btn sm" data-g="vnew">رمز جدید</button><button class="btn sm" data-g="vprint"><i data-lucide="printer"></i>نسخهٔ کاغذی</button></div>`;
    h+=P.players.map(p=>`<div style="display:grid;gap:6px"><b style="color:${p.color}">${esc(p.symbol+' '+p.name)} · مرحله ${fa(v.stage[p.id]||0)} از ۳</b><div class="row"><button class="btn sm ok" data-g="vissue" data-p="${p.id}">مرحله موفق · رمز بعدی</button><button class="btn sm" data-g="vreset" data-p="${p.id}">ترتیب اشتباه</button><button class="btn sm pri" data-g="vunlock" data-p="${p.id}">باز کردن کیف</button></div></div>`).join('')}
  else{h+=pBtns('win','برد {n} +'+fa(R),'ok');if(g==='cup')h+=`<div class="row"><button class="btn sm" data-g="hold">⏱ اعتبارسنجی ۲ ثانیه روی صفحه</button><button class="btn sm" data-g="foul">🚨 خطای دست دوم</button></div>`}
  h+=`<div class="row" style="border-top:1px solid var(--line);padding-top:10px"><span class="muted">جایزهٔ این راند: ${fa(R)} ${esc(P.unit)}</span>${g!=='generic'&&g!=='cup'&&g!=='mitts'?pBtns('win','برد {n}').replace('<div class="row">','').replace(/<\/div>$/,''):''}</div></div>`;
  el.innerHTML=h;icons(el);renderQuickLines()}
function renderQuickLines(){const el=$('#quickLines');if(!el)return;const s=P.segments[curSegIndex()];el.innerHTML=s&&s.lines.length?s.lines.map((l,i)=>`<button class="btn sm" data-ql="${i}" title="${esc(EMO[l.emotion].fa)}">${vstat(l)==='ready'?'🔊':'🔇'} ${esc(l.text.slice(0,42))}${l.text.length>42?'…':''}</button>`).join(''):'<span class="muted">این مرحله دیالوگی ندارد.</span>'}
function renderJournal(){const el=$('#journal');if(!el)return;const u=undoneSet();const J=[...G().journal].reverse();el.innerHTML=J.map(e=>{const p=pl(e.player);const d=e.kind==='score'?(e.delta>0?'+':'')+fa(e.delta):e.kind==='undo'?'↶':e.kind.startsWith('var')?'VAR':e.kind==='vault'?'🔓':'';
  return `<li class="${u.has(e.id)?'undone':''}"><span class="muted">${new Date(e.t).toLocaleTimeString('fa-IR')}</span><span>${p?`<b style="color:${p.color}">${esc(p.name)}</b> · `:''}${esc(e.reason)}</span><span class="d">${d}</span></li>`}).join('')||'<li><span></span><span class="muted">هنوز رویدادی ثبت نشده.</span><span></span></li>'}
function renderTransport(){const b=$('#tPlay');const live=st.live>=0;b.innerHTML=`<i data-lucide="${live&&st.playing?'pause':'play'}"></i><span>${!live?'اجرا از مرحلهٔ انتخابی':st.playing?'مکث':'ادامه'}</span>`;$('#tAuto').checked=!!P.autoAdvance;icons(b);renderNow()}
function renderNow(){const seg=P.segments[st.live];$('#nowLine').innerHTML=seg?`<b>${fa(st.live+1)} · ${esc(seg.title)}</b>${st.line?' · '+esc(st.line.text.slice(0,60)):''}`:'آماده'}
let tallyKey='';function renderTally(){const rec=st.rec&&st.rec.state==='recording';const secs=rec?Math.floor((performance.now()-st.recT0)/1000):0;const key=`${st.mode}|${rec}|${secs}|${st.live>=0&&st.playing}|${G().var}|${Math.ceil(st.timer.remain)}`;if(key===tallyKey)return;tallyKey=key;
  $('#tally').innerHTML=(rec?`<span class="tag rec">● ضبط ${fa(String(Math.floor(secs/60)).padStart(2,'0'))}:${fa(String(secs%60).padStart(2,'0'))}</span>`:'')+(G().var?'<span class="tag var">VAR</span>':'')+(st.mode==='rehearsal'?'<span class="tag reh">تمرین</span>':'')+(st.live>=0&&!st.playing?'<span class="tag">مکث</span>':'')+(st.live<0?'<span class="tag">پیش‌نمایش</span>':'');
  $('#timerRead').textContent=fa(Math.ceil(st.timer.remain))+'s'}
function renderRecBtn(){const b=$('#recBtn');const on=!!st.rec;b.innerHTML=on?'<i data-lucide="square"></i><span>پایان ضبط و ذخیره</span>':'<i data-lucide="circle"></i><span>شروع ضبط از مرحلهٔ انتخاب‌شده</span>';icons(b);const m=pickMime();$('#recInfo').textContent=m?`${S.quality} · ${fa(S.fps)}fps · ${m.includes('mp4')?'MP4 (H.264/AAC)':'WebM (VP9/Opus)'} · صدای استریو ۴۸kHz · زیرنویس SRT کنار ویدیو`:'ضبط در این مرورگر ممکن نیست'}
async function renderPreflight(){const lines=allLines();const ready=lines.filter(x=>vstat(x.l)==='ready').length;const mime=pickMime();let persisted=false,est=null;try{persisted=navigator.storage&&await navigator.storage.persisted();est=navigator.storage&&await navigator.storage.estimate()}catch(e){}
  const issues=P.segments.filter(s=>s.status==='issue'||s.issue).length;const drafts=P.segments.filter(s=>s.status==='draft').length;const sw=!!(navigator.serviceWorker&&navigator.serviceWorker.controller);
  const items=[[st.fonts?'y':'w',st.fonts?'فونت‌های نمایش (داخل اپ) آماده':'فونت‌ها هنوز بارگذاری نشده‌اند'],
    [ready===lines.length?'y':'n',`صدای آفلاین: ${fa(ready)} از ${fa(lines.length)} دیالوگ نصب شده`],
    [issues?'n':'y',issues?`${fa(issues)} مرحله ایراد ثبت‌شده دارد`:'ایراد ثبت‌شده‌ای نیست'],
    [drafts?'w':'y',drafts?`${fa(drafts)} مرحله هنوز پیش‌نویس است`:'همهٔ مراحل تأیید شده‌اند'],
    [P.logo?'y':'w',P.logo?'لوگو آماده':'لوگو تنظیم نشده'],
    [mime?'y':'n',mime?`فرمت ضبط: ${mime.includes('mp4')?'MP4 (H.264)':'WebM'} · ${S.quality} · ${S.fps}fps`:'ضبط ویدیو در این مرورگر پشتیبانی نمی‌شود'],
    [sw?'y':'w',sw?'اپ روی دستگاه نصب و بدون اینترنت قابل اجراست':'حالت آفلاین کامل فعال نیست (اپ را از آدرس https باز کنید)'],
    [persisted?'y':'w',persisted?'ذخیرهٔ دائمی فعال است':'ذخیرهٔ دائمی فعال نیست (صفحهٔ صدا)'+(est?` · فضای آزاد ${fmtSize(est.quota-est.usage)}`:'')],
    [G().var?'w':'y',G().var?'VAR هنوز روشن است':'VAR خاموش است']];
  const ic={y:'check-circle-2',n:'x-circle',w:'alert-triangle'};$('#preflight').innerHTML=items.map(([k,l])=>`<li><i data-lucide="${ic[k]}" class="${k}"></i><span>${l}</span></li>`).join('');icons($('#preflight'))}
function renderSfx(){$('#sfxPad').innerHTML=Object.entries(SFX_LIST).map(([k,v])=>`<button data-sfx="${k}">${v}</button>`).join('')}
function renderControl(){$('#projName').value=P.name;if(st.sel>=P.segments.length)st.sel=Math.max(0,P.segments.length-1);renderROS();renderInspector();renderScores();renderTransport();renderGameDeck();renderJournal();renderPreflight();renderRecBtn();$('#guides').classList.toggle('hidden',!P.layout.guides)}

/* ---------------- pages ---------------- */
function renderBrief(){const b=P.brief;const el=$('#briefOut');if(!b){el.innerHTML='<p class="muted">هنوز تحلیلی انجام نشده. بعد از «درک کامل با هوش مصنوعی»، خلاصه، لحن، شخصیت‌ها، ضرب‌آهنگ و یادداشت‌های کارگردان اینجا می‌آید.</p>';return}const li=a=>(a||[]).map(x=>`<li>${esc(x)}</li>`).join('');
  el.innerHTML=`${b.summary?`<div><h3>خلاصه</h3><p class="prose" style="margin:0">${esc(b.summary)}</p></div>`:''}${b.tone?`<div><h3>لحن کلی</h3><p class="prose" style="margin:0">${esc(b.tone)}</p></div>`:''}${b.characters&&b.characters.length?`<div><h3>شخصیت‌ها</h3><ul>${li(b.characters)}</ul></div>`:''}${b.beats&&b.beats.length?`<div><h3>ضرب‌آهنگ و مراحل</h3><ul>${li(b.beats)}</ul></div>`:''}${b.directorNotes&&b.directorNotes.length?`<div><h3>یادداشت‌های کارگردان</h3><ul>${li(b.directorNotes)}</ul></div>`:''}`}
function introGroups(){const out=[];P.segments.forEach((s,i)=>{if(s.type==='intro'){let end=i;while(P.segments[end+1]&&['rules','countdown'].includes(P.segments[end+1].type)&&P.segments[end+1].type!=='intro')end++;out.push({start:i,end,seg:s})}});return out}
function renderIntro(){$('#gGame').innerHTML=optList(GAMES,'generic');const gs=introGroups();
  $('#introList').innerHTML=gs.map((x,k)=>{const lines=P.segments.slice(x.start,x.end+1).flatMap(s=>s.lines);const ready=lines.filter(l=>vstat(l)==='ready').length;return `<div class="intro-item" data-k="${k}"><div><strong>${esc(x.seg.title)}</strong><div class="muted">${esc(GAMES[x.seg.game])} · مراحل ${fa(x.start+1)} تا ${fa(x.end+1)} · صدا ${fa(ready)}/${fa(lines.length)}</div></div>
    <div class="row" style="gap:4px"><button class="btn sm" data-ia="preview"><i data-lucide="eye"></i>پیش‌نمایش</button><button class="btn sm" data-ia="edit">ویرایش</button><button class="btn sm pri" data-ia="rec"><i data-lucide="circle"></i>ضبط جدا</button></div></div>`}).join('')||'<p class="empty">هنوز معرفی‌ای نیست. از فرم کنار بسازید یا در سناریو مرحلهٔ «معرفی» اضافه کنید.</p>';icons($('#introList'))}
function renderVoice(){const lines=allLines();const ready=lines.filter(x=>vstat(x.l)==='ready').length;$('#vCount').textContent=`${fa(ready)}/${fa(lines.length)}`;$('#vProg').style.transform=`scaleX(${lines.length?ready/lines.length:0})`;
  $('#vNote').textContent=ready===lines.length?'همهٔ دیالوگ‌ها نصب و آفلاین آماده‌اند. سر صحنه اینترنت لازم نیست.':`${fa(lines.length-ready)} دیالوگ هنوز صدای نصب‌شده ندارد.`;
  let html='';P.segments.forEach((s,si)=>{if(!s.lines.length)return;html+=`<table class="table" style="margin-bottom:22px"><tr><th colspan="3">${fa(si+1)} · ${esc(s.title)} <span class="muted">(${TYPES[s.type]})</span></th></tr>`+s.lines.map((l,li)=>{const v=vstat(l);const r=lineRec(l);return `<tr data-si="${si}" data-li="${li}"><td><span class="vchip ${v}">${VLABEL[v]}</span></td><td class="txt">${esc(l.text)}<div class="muted">${esc(spk(l.speaker).name)} · ${EMO[l.emotion].fa}${l.direction?' · '+esc(l.direction):''}${r?' · '+({gemini:'Gemini',openai:'OpenAI',edge:'دلارا',mic:'میکروفون',file:'فایل',pack:'بستهٔ نصبی',piper:'موتور اضطراری'}[r.source]||''):''}</div></td><td><div class="row" style="flex-wrap:nowrap;gap:4px"><button class="btn sm icon" data-va="play" title="پخش"><i data-lucide="volume-2"></i></button><button class="btn sm" data-va="gen"><i data-lucide="sparkles"></i>${v==='ready'?'دوباره':'ساخت'}</button></div></td></tr>`}).join('')+'</table>'});
  $('#voiceTable').innerHTML=html||'<p class="empty">هنوز دیالوگی نیست.</p>';
  const dv=faVoices().filter(v=>/^fa/i.test(v.lang));
  $('#speakers').innerHTML=P.speakers.map((p,i)=>{const vopts=p.provider==='openai'?OPENAI_VOICES.map(v=>`<option ${v===p.voice?'selected':''}>${v}</option>`).join(''):p.provider==='gemini'?GEMINI_VOICES.map(([v,d])=>`<option value="${v}" ${v===p.voice?'selected':''}>${v} · ${d}</option>`).join(''):p.provider==='piper'?`<option>${esc(p.voice||'fa_IR-amir-medium')}</option>`:p.provider==='edge'?EDGE_VOICES.map(([v,d])=>`<option value="${v}" ${v===p.voice?'selected':''}>${d}</option>`).join(''):'<option value="">—</option>';
    return `<div class="line" data-sp="${i}"><div class="grid2"><label class="f">نام<input type="text" data-spf="name" value="${esc(p.name)}"></label><label class="f">موتور<select data-spf="provider">${Object.entries(PROVIDERS).map(([k,v])=>`<option value="${k}" ${p.provider===k?'selected':''}>${v}</option>`).join('')}</select></label></div>
    <label class="f">صدا<select data-spf="voice">${vopts}</select></label><div class="row"><button class="btn sm" data-spa="test"><i data-lucide="volume-2"></i>تست این صدا با لحن هیجان‌زده</button>${P.speakers.length>1?'<button class="btn sm ghost" data-spa="del">حذف</button>':''}</div></div>`}).join('')+`<p class="muted">پیشنهاد برای مجری زن جذاب: Leda (جوان)، Aoede (نسیمی)، Zephyr (روشن)، Kore (محکم). هر صدا را با دکمهٔ تست بشنوید و بعد همه را بسازید. صدای فارسی روی این دستگاه برای تمرین: ${dv.length?esc(dv.map(v=>v.name).join('، ')):'ندارد'}.</p>`;
  storageInfo();icons($('#view-voice'))}
async function storageInfo(){try{const e=await navigator.storage.estimate();const p=await navigator.storage.persisted();$('#storageInfo').textContent=`${p?'دائمی ✓':'موقت'} · استفاده ${fmtSize(e.usage)}`}catch(e){}}
function renderLook(){const th=P.theme;$('#themes').innerHTML=THEMES.map((t,i)=>`<button class="theme-sw" data-th="${i}" aria-pressed="${t.name===th.name}"><span class="pv" style="background:radial-gradient(circle at 50% 40%,${t.bg2},${t.bg1});color:${t.ink};text-shadow:0 3px 0 ${t.shade}"><span style="position:absolute;inset:auto 0 0 0;height:12px;background:${t.accent}"></span><span style="position:absolute;top:10px;left:10px;width:22px;height:22px;border-radius:50%;background:${t.accent2}"></span>داداش‌مود</span><span class="nm">${t.name}</span></button>`).join('');
  $('#colors').innerHTML=Object.entries(COLOR_KEYS).map(([k,l])=>`<label><input type="color" data-col="${k}" value="${th[k]}">${l}</label>`).join('');
  $('#lyFont').innerHTML=optList(FONTS,th.font);$('#lyScore').value=P.layout.score;$('#lyTimer').value=P.layout.timer;$('#lySub').value=P.layout.sub;$('#lySubV').textContent=fa(P.layout.sub);$('#lyGreen').checked=P.layout.green;$('#lyGuides').checked=P.layout.guides;
  $('#unitIn').value=P.unit;$('#startIn').value=P.startBank;
  $('#playersEdit').innerHTML=P.players.map((p,i)=>`<div class="row" data-pe="${i}" style="padding:6px 0;border-bottom:1px solid var(--line);flex-wrap:nowrap"><input type="color" data-pf="color" value="${p.color}" style="width:40px;height:36px;border:1px solid var(--line2);border-radius:8px;padding:2px"><input type="text" data-pf="name" value="${esc(p.name)}"><input type="text" data-pf="symbol" value="${esc(p.symbol)}" style="width:56px;text-align:center" aria-label="نماد"><input type="text" data-pf="key" value="${esc(p.key)}" maxlength="1" style="width:48px;text-align:center" aria-label="کلید"><button class="btn sm icon ghost" data-pdel="${i}" title="حذف"><i data-lucide="x"></i></button></div>`).join('');
  const lg=P.logo;$('#logoOrig').innerHTML=lg?`<img src="${lg.orig}" alt="لوگوی اصلی">`:'<span class="muted">لوگویی نیست</span>';$('#logoCut').innerHTML=lg&&lg.cut?`<img src="${lg.cut}" alt="لوگوی جداشده">`:'<span class="muted">—</span>';$('#logoTol').value=lg?lg.tol:42;$('#tolV').textContent=fa($('#logoTol').value);icons($('#view-look'))}
async function renderProjects(){const ps=(await DB.all('projects')).sort((a,b)=>(b.updated||0)-(a.updated||0));
  $('#projList').innerHTML=ps.map(p=>`<div class="proj-row ${p.id===P.id?'cur':''}" data-pid="${p.id}"><div><strong>${esc(p.name)}</strong><div class="muted">${fa((p.segments||[]).length)} مرحله · ${new Date(p.updated||p.created).toLocaleDateString('fa-IR')}</div></div><div class="row" style="gap:4px"><button class="btn sm" data-pa="open">باز کردن</button><button class="btn sm ghost" data-pa="dup">کپی برای ویدیوی بعدی</button><button class="btn sm ghost" data-pa="exp">خروجی</button><button class="btn sm ghost" data-pa="del">حذف</button></div></div>`).join('')}
async function renderTakes(){const ts=(await DB.all('takes')).sort((a,b)=>b.date-a.date);$('#takes').innerHTML=ts.map(t=>`<div class="proj-row take" data-tid="${t.id}" style="grid-template-columns:1fr"><div><strong style="font-size:14.5px">${esc(t.name)}</strong><div class="muted">${fmtSize(t.size)} · ${fa(Math.round(t.dur||0))} ثانیه · ${t.mime.includes('mp4')?'MP4':'WebM'} · ${t.res||''} ${t.fps?fa(t.fps)+'fps':''}</div><div class="row" style="margin-top:8px;gap:4px"><button class="btn sm" data-ta="view"><i data-lucide="play"></i>تماشا</button><button class="btn sm" data-ta="dl"><i data-lucide="download"></i>دانلود</button>${t.srt?'<button class="btn sm" data-ta="srt"><i data-lucide="file-text"></i>زیرنویس SRT</button>':''}<button class="btn sm" data-ta="share"><i data-lucide="share-2"></i>اشتراک / فضای ابری</button><button class="btn sm ghost" data-ta="del">حذف</button></div></div></div>`).join('')||'<p class="empty">هنوز ضبطی انجام نشده. در اتاق کنترل ← تمرین و ضبط ← حالت «ضبط».</p>';icons($('#takes'))}
async function renderSettings(){$('#sProv').value=S.aiProvider;$('#sGKey').value=S.geminiKey;$('#sGChat').value=S.geminiChat;$('#sGTts').value=S.geminiTts;$('#sOKey').value=S.openaiKey;$('#sOBase').value=S.openaiBase;$('#sOChat').value=S.openaiChat;$('#sOTts').value=S.openaiTts;
  $('#sQual').value=S.quality;$('#sFps').value=String(S.fps);$('#sAutoDl').checked=S.autoDl;$('#sDevTts').checked=S.devTts;$('#sNorm').checked=S.normalize;$('#sBed').checked=S.musicBed;$('#sWake').checked=S.wake;$('#sSfx').value=S.sfxVol;$('#sVoice').value=S.voiceVol;
  const m=pickMime();$('#codecInfo').textContent=m?`این مرورگر با ${m.includes('mp4')?'MP4 / H.264 (مستقیم قابل آپلود در یوتیوب)':'WebM / VP9 (یوتیوب مستقیم قبول می‌کند)'} ضبط می‌کند. بیت‌ریت ویدیو ${fa(Math.round(QUAL[S.quality].br*(S.fps==60?1.3:1)/1e6))} مگابیت (بالاتر از پیشنهاد یوتیوب)، صدا ۳۲۰ کیلوبیت.`:'این مرورگر ضبط ویدیو ندارد؛ کروم یا اج را استفاده کنید.';
  try{const h=await DB.get('kv','folder');$('#folderInfo').textContent=h?'پوشه: '+h.name:''}catch(e){}
  $('#swInfo').textContent=navigator.serviceWorker&&navigator.serviceWorker.controller?'✓ نصب آفلاین فعال است':'نصب آفلاین هنوز فعال نیست'}

/* ---------------- actions ---------------- */
async function genLine(ln,btn){if(!ln.text.trim()){toast('متن دیالوگ خالی است');return}if(btn){btn.disabled=true;btn.textContent='در حال ساخت...'}
  try{await synthLine(ln);toast('صدا ساخته و روی دستگاه نصب شد');previewLine(ln)}catch(e){toast(e.message,5000)}finally{refreshVoiceBits()}}
function refreshVoiceBits(){renderROS();if(!$('#view-control').classList.contains('hidden'))renderInspector();if(!$('#view-voice').classList.contains('hidden'))renderVoice();if(!$('#view-intro').classList.contains('hidden'))renderIntro();renderQuickLines();renderPreflight()}
async function micToggle(ln,btn){if(st.mic){st.mic.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:true,autoGainControl:true,sampleRate:48000,channelCount:1}});const mr=new MediaRecorder(stream);const ch=[];mr.ondataavailable=e=>ch.push(e.data);mr.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());st.mic=null;await saveAudio(ln,new Blob(ch,{type:mr.mimeType}),'mic');toast('صدای شما نصب شد');refreshVoiceBits()};mr.start();st.mic=mr;btn.innerHTML='■ توقف ضبط';btn.classList.add('pri')}catch(e){toast('دسترسی میکروفون داده نشد')}}
function lineAt(si,li){return P.segments[si]&&P.segments[si].lines[li]}
function showView(v){$$('#tabs button').forEach(b=>b.setAttribute('aria-selected',b.dataset.view===v));$$('main>section').forEach(s=>s.classList.toggle('hidden',s.id!=='view-'+v));
  if(v==='control')renderControl();if(v==='voice')renderVoice();if(v==='look')renderLook();if(v==='projects'){renderProjects();renderTakes()}if(v==='settings')renderSettings();if(v==='intro')renderIntro();if(v==='script'){$('#scriptText').value=P.script||'';renderBrief()}}
$('#tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view)});
document.addEventListener('click',e=>{const x=e.target.closest('[data-go]');if(x)showView(x.dataset.go)});
$('#deckTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-deck]');if(!b)return;$$('#deckTabs button').forEach(x=>x.setAttribute('aria-selected',x===b));$$('.deck [data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==b.dataset.deck));if(b.dataset.deck==='rehearse')renderPreflight()});
$('#projName').addEventListener('input',e=>{P.name=e.target.value;save()});
/* run of show */
$('#ros').addEventListener('click',e=>{const it=e.target.closest('.ros-item');if(!it)return;const i=+it.dataset.i;const act=e.target.closest('[data-act]')?.dataset.act;
  if(act==='cue'){goLive(i);return}if(act==='up'||act==='down'){const j=act==='up'?i-1:i+1;if(j<0||j>=P.segments.length)return;const a=P.segments;[a[i],a[j]]=[a[j],a[i]];if(st.sel===i)st.sel=j;if(st.live===i)st.live=j;else if(st.live===j)st.live=i;save();renderROS();renderInspector();return}
  st.sel=i;renderROS();renderInspector();renderGameDeck()});
$('#ros').addEventListener('dblclick',e=>{const it=e.target.closest('.ros-item');if(it)goLive(+it.dataset.i)});
$('#newSegType').innerHTML=optList(TYPES,'dialogue');
$('#addSeg').onclick=()=>{const type=$('#newSegType').value;P.segments.splice(st.sel+1,0,mkSeg({type,title:TYPES[type].split(' (')[0]}));st.sel=Math.min(st.sel+1,P.segments.length-1);save();renderControl()};
$('#dupSeg').onclick=()=>{const s=P.segments[st.sel];if(!s)return;const c=JSON.parse(JSON.stringify(s));c.id=uid();c.lines.forEach(l=>l.id=uid());P.segments.splice(st.sel+1,0,c);st.sel++;save();renderControl()};
let delArm=0;$('#delSeg').onclick=()=>{if(!P.segments[st.sel])return;if(Date.now()-delArm>2500){delArm=Date.now();toast('برای حذف این مرحله دوباره بزنید');return}if(st.live===st.sel)stopAll();P.segments.splice(st.sel,1);st.sel=Math.max(0,st.sel-1);save();renderControl()};
/* inspector */
$('#insp').addEventListener('input',e=>{const s=P.segments[st.sel];if(!s)return;const f=e.target.dataset.f,lf=e.target.dataset.lf;
  if(f){if(f==='rules')s.rules=e.target.value.split('\n').map(x=>x.trim()).filter(Boolean);else if(f==='duration')s.duration=Math.max(5,+e.target.value||30);else if(f==='reward')s.reward=+e.target.value||0;else if(!['type','winner','game'].includes(f))s[f]=e.target.value;save();if(f==='title'||f==='issue')renderROS();return}
  if(lf){const k=+e.target.closest('.line').dataset.li;const ln=s.lines[k];ln[lf]=e.target.value;save();const chipEl=e.target.closest('.line').querySelector('.vchip');const v=vstat(ln);chipEl.className='vchip '+v;chipEl.textContent=VLABEL[v]}});
$('#insp').addEventListener('change',e=>{const s=P.segments[st.sel];if(!s)return;const f=e.target.dataset.f;
  if(f==='type'||f==='game'){s[f]=e.target.value;save();renderROS();renderInspector();renderGameDeck();return}if(f==='winner'){s.winner=e.target.value;save();return}if(f)renderPreflight();
  if(e.target.dataset.la==='file'){const file=e.target.files[0];const k=+e.target.closest('.line').dataset.li;if(file)saveAudio(s.lines[k],file,'file').then(()=>{toast('فایل صدا نصب شد');refreshVoiceBits()})}
  if(e.target.dataset.lf==='emotion'||e.target.dataset.lf==='speaker'){renderROS();renderInspector()}});
$('#insp').addEventListener('click',e=>{const s=P.segments[st.sel];if(!s)return;const sp=e.target.closest('.status-pick button');if(sp){s.status=sp.dataset.v;save();renderROS();renderInspector();renderPreflight();return}
  const b=e.target.closest('button[data-la]');if(!b)return;const la=b.dataset.la;if(la==='add'){s.lines.push({id:uid(),speaker:P.speakers[0].id,emotion:'warm',text:'',direction:''});save();renderInspector();renderROS();const ts=$$('#insp textarea[data-lf=text]');ts[ts.length-1]?.focus();return}
  const k=+b.closest('.line').dataset.li;const ln=s.lines[k];
  if(la==='play')previewLine(ln);else if(la==='cue')cueLine(ln);else if(la==='gen')genLine(ln,b);else if(la==='mic')micToggle(ln,b);
  else if(la==='del'){s.lines.splice(k,1);save();renderInspector();renderROS()}else if(la==='up'&&k>0){[s.lines[k-1],s.lines[k]]=[s.lines[k],s.lines[k-1]];save();renderInspector()}});
/* transport */
$('#tPlay').onclick=togglePlay;$('#tNext').onclick=()=>{const i=(st.live>=0?st.live:st.sel)+1;if(i<P.segments.length)goLive(i)};$('#tPrev').onclick=()=>{const i=(st.live>=0?st.live:st.sel)-1;if(i>=0)goLive(i)};
$('#tRestart').onclick=()=>goLive(st.live>=0?st.live:st.sel);$('#tStop').onclick=()=>{if(st.rec)stopRecording();else stopAll()};$('#tFull').onclick=()=>{(cv.requestFullscreen||cv.webkitRequestFullscreen||(()=>{})).call(cv)};
$('#tAuto').onchange=e=>{P.autoAdvance=e.target.checked;save()};
/* bank + game deck */
$('#scores').addEventListener('click',async e=>{const b=e.target.closest('[data-sc]');if(!b)return;const p=P.players[+b.closest('.pbank').dataset.pi];await AE.resume();award(p.id,b.dataset.sc==='+'?S.step:-S.step,b.dataset.sc==='+'?'امتیاز دستی':'کسر دستی')});
$('#stepCtl').onclick=e=>{const b=e.target.closest('button');if(!b)return;S.step=+b.dataset.step;saveS();renderScores()};
$('#undoBtn').onclick=undoLast;$('#varBtn').onclick=async()=>{await AE.resume();setVar(!G().var)};
$('#tmToggle').onclick=()=>{if(st.timer.remain<=0)st.timer.remain=st.timer.total;st.timer.running=!st.timer.running};$('#tmPlus').onclick=()=>{st.timer.remain+=10;st.timer.total=Math.max(st.timer.total,st.timer.remain)};
$('#tmReset').onclick=()=>{const s=P.segments[curSegIndex()];const d=(s&&s.duration)||30;st.timer={total:d,remain:d,running:false,lastSec:99}};$('#holdBtn').onclick=async()=>{await AE.resume();startHold(2)};
$('#gameDeck').addEventListener('click',async e=>{const b=e.target.closest('[data-g]');if(!b)return;await AE.resume();const pid=b.dataset.p,v=b.dataset.v,a=b.dataset.g;
  ({win:()=>roundWin(pid),dlock:()=>distLock(pid,v),dhit:()=>distAttempt(pid,true),dmiss:()=>distAttempt(pid,false),mnew:mysteryNew,mpick:()=>mysteryPick(pid,+v),mreveal:()=>mysteryReveal(pid),mitts:()=>mittsWin(pid),
    pbuy:()=>powerBuy(pid,v,$(`[data-stake="${pid}"]`)?.value),pres:()=>powerResolve(pid,+v,b.dataset.ok==='1'),vnew:vaultNew,vissue:()=>vaultIssue(pid),vreset:()=>vaultResetStage(pid),vunlock:()=>vaultUnlock(pid),hold:()=>startHold(2),
    foul:()=>{AE.whistle();AE.siren();fxPush('miss',{})},vprint:printCodes})[a]?.();setTimeout(renderGameDeck,50)});
function printCodes(){const v=G().vault;if(!v.codes.length){toast('اول رمز بسازید');return}const w=window.open('','_blank');if(!w){toast('پنجرهٔ چاپ باز نشد');return}w.document.write(`<html dir="rtl"><body style="font-family:Vazirmatn,Tahoma;padding:40px"><h1>${esc(P.name)}</h1><h2>رمزهای کیف طلایی (نسخهٔ کاغذی پشتیبان)</h2><p style="font-size:64px;letter-spacing:.3em">${v.codes.map(c=>fa(c)).join(' ')}</p><p>رمز ۱: ${fa(v.codes[0])} · رمز ۲: ${fa(v.codes[1])} · رمز ۳: ${fa(v.codes[2])}</p><script>print()<\/script></body></html>`);w.document.close()}
/* mode + rehearsal */
$('#modeCtl').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(st.rec){toast('اول ضبط را تمام کنید');return}st.mode=b.dataset.mode;$$('#modeCtl button').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#rehearsePanel').classList.toggle('hidden',st.mode!=='rehearsal');$('#recordPanel').classList.toggle('hidden',st.mode!=='record');renderPreflight();renderRecBtn()};
$('#recBtn').onclick=()=>st.rec?stopRecording():startRecording(false);
$('#recWarn').addEventListener('click',e=>{if(e.target.id==='recAnyway')startRecording(true)});
$('#testStart').onclick=()=>{const i=P.segments.findIndex(s=>s.type==='countdown');if(i>=0)goLive(i);else toast('مرحلهٔ شمارش معکوس ندارید')};
$('#testSound').onclick=async()=>{await AE.resume();AE.ding();const first=allLines().find(x=>vstat(x.l)==='ready');setTimeout(()=>{if(first){previewLine(first.l);toast('پخش: '+first.l.text.slice(0,40))}else toast('هنوز صدای نصب‌شده ندارید؛ فقط صدای افکت پخش شد')},500)};
$('#testAnim').onclick=()=>goLive(st.sel);
$('#testScore').onclick=async()=>{await AE.resume();const p=P.players[secureRandInt(P.players.length)];if(!p)return;const ev=award(p.id,S.step,'تست امتیاز (تمرین)');if(ev)setTimeout(undoLast,1800);toast('امتیاز آزمایشی اضافه و بعد برگردانده شد')};
let chainTok=0;$('#testAllVoice').onclick=async()=>{await AE.resume();const my=++chainTok;const ls=allLines();let miss=0;toast('پخش همهٔ صداها؛ برای توقف دوباره بزنید');for(const x of ls){if(my!==chainTok)return;const b=await getBuf(x.l);if(!b){miss++;continue}await new Promise(r=>{const s=AE.play(b.b,AE.voice,b.gain);s.onended=r});await sleep(200)}if(my===chainTok)toast(miss?`${fa(miss)} دیالوگ صدا نداشت`:'همهٔ صداها سالم پخش شدند ✓',4000);chainTok++};
$('#testDry').onclick=()=>{P.autoAdvance=true;renderTransport();goLive(0);toast('اجرای کامل از مرحلهٔ ۱ (مرحله‌های بازی زنده را دستی رد کنید)')};
$('#sfxPad').addEventListener('click',async e=>{const b=e.target.closest('[data-sfx]');if(!b)return;await AE.resume();AE[b.dataset.sfx]&&AE[b.dataset.sfx]()});
$('#quickLines').addEventListener('click',e=>{const b=e.target.closest('[data-ql]');if(!b)return;const s=P.segments[curSegIndex()];cueLine(s.lines[+b.dataset.ql])});
$('#exportJournal').onclick=()=>{const rows=[['زمان','بازیکن','تغییر','شرح','مرحله']].concat(G().journal.map(e=>[new Date(e.t).toISOString(),pl(e.player)?.name||'',e.delta,e.reason,(e.seg??-1)+1]));download(new Blob(['\ufeff'+rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv'}),safeName(P.name)+' - journal.csv')};
let resetArm=0;$('#resetGame').onclick=()=>{if(Date.now()-resetArm>2500){resetArm=Date.now();toast('بانک‌ها به مقدار اولیه برمی‌گردند و دفتر خالی می‌شود. برای تأیید دوباره بزنید');return}resetGame();toast('مسابقهٔ جدید آماده است')};
$('#aiAsk').onclick=async e=>{const q=$('#aiQ').value.trim();if(!q)return;const b=e.currentTarget;b.disabled=true;$('#aiOut').innerHTML='<p class="muted">در حال فکر کردن...</p>';
  try{const j=await askDirector(q);$('#aiOut').innerHTML=`<div class="ai-answer"><div>${esc(j.answer)}</div>${j.suggestedAction?`<div class="muted">پیشنهاد: ${esc(j.suggestedAction)}</div>`:''}${j.sayLine?`<div><b>جملهٔ مجری:</b> «${esc(j.sayLine)}»</div><div class="row"><button class="btn sm" id="aiAddLine" data-t="${esc(j.sayLine)}" data-e="${esc(j.emotion||'referee')}">افزودن به دیالوگ‌های همین مرحله</button></div>`:''}</div>`}catch(err){$('#aiOut').innerHTML=`<p class="muted">${esc(err.message)}</p>`}finally{b.disabled=false}};
$('#aiOut').addEventListener('click',e=>{if(e.target.id!=='aiAddLine')return;const s=P.segments[curSegIndex()];s.lines.push({id:uid(),speaker:P.speakers[0].id,emotion:EMO[e.target.dataset.e]?e.target.dataset.e:'referee',text:e.target.dataset.t,direction:''});save();renderInspector();renderQuickLines();toast('اضافه شد؛ دکمهٔ «ساخت صدا» را بزنید')});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return;if($('#view-control').classList.contains('hidden'))return;const k=e.key.toLowerCase();
  if(k===' '){e.preventDefault();togglePlay()}else if(e.key==='ArrowLeft')$('#tNext').click();else if(e.key==='ArrowRight')$('#tPrev').click();else if(k==='r')$('#tRestart').click();else if(k==='t')$('#tmToggle').click();else if(k==='f')$('#tFull').click();else if(k==='v')$('#varBtn').click();else if(k==='z')undoLast();else if(k==='h')$('#holdBtn').click();
  else{const pk=P.players.find(p=>p.key&&p.key.toLowerCase()===k);if(pk){AE.resume().then(()=>roundWin(pk.id));return}const m=e.code.match(/^Digit([1-6])$/);if(m){const p=P.players[+m[1]-1];if(p)AE.resume().then(()=>award(p.id,e.shiftKey?-S.step:S.step,e.shiftKey?'کسر دستی':'امتیاز دستی'))}}});
/* script page */
$('#scriptText').addEventListener('input',e=>{P.script=e.target.value;save()});
$('#scriptFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();if(/\.json$/i.test(f.name)){try{await importEpisodeJSON(JSON.parse(t));e.target.value='';return}catch(err){}}$('#scriptText').value=t;P.script=t;save();toast('متن بارگذاری شد؛ حالا تبدیل کنید');e.target.value=''};
$('#emoList').textContent=Object.values(EMO).map(v=>v.fa).join('، ');
$('#offParse').onclick=()=>{const{meta,segs}=parseOffline($('#scriptText').value);if(!segs.length){$('#parseMsg').textContent='چیزی برای تبدیل پیدا نشد.';return}applyEpisodeMeta(meta);const n=applySegments(segs,$('#parseAppend').checked);$('#parseMsg').textContent=`${fa(n)} مرحله ساخته شد. در اتاق کنترل بررسی کنید.`};
$('#aiParse').onclick=async e=>{const txt=$('#scriptText').value.trim();if(!txt){toast('اول متن سناریو را وارد کنید');return}const b=e.currentTarget;b.disabled=true;$('#parseMsg').textContent='هوش مصنوعی در حال خواندن کل سناریو و دفتر کارگردانی است...';
  try{const j=await aiJSON(AI_SYS,txt);P.brief=j.brief||P.brief;if(!$('#parseAppend').checked)applyEpisodeMeta(j.episode);const n=applySegments(j.segments||[],$('#parseAppend').checked);renderBrief();$('#parseMsg').textContent=`${fa(n)} مرحله با دیالوگ و لحن ساخته شد. حالا در «صدا و گوینده» همهٔ صداها را بسازید.`}catch(err){$('#parseMsg').textContent=err.message+' · می‌توانید از تبدیل آفلاین استفاده کنید.'}finally{b.disabled=false}};
/* intro studio */
$('#introList').addEventListener('click',e=>{const b=e.target.closest('[data-ia]');if(!b)return;const x=introGroups()[+b.closest('[data-k]').dataset.k];if(!x)return;const a=b.dataset.ia;
  if(a==='preview'){showView('control');goLive(x.start)}else if(a==='edit'){st.sel=x.start;showView('control')}else if(a==='rec'){st.mode='record';showView('control');$$('#modeCtl button').forEach(z=>z.setAttribute('aria-pressed',z.dataset.mode==='record'));$('#rehearsePanel').classList.add('hidden');$('#recordPanel').classList.remove('hidden');$$('#deckTabs button').forEach(z=>z.setAttribute('aria-selected',z.dataset.deck==='rehearse'));$$('.deck [data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!=='rehearse'));startRecording(false,{start:x.start,end:x.end,label:'معرفی '+x.seg.title})}});
$('#aiGame').onclick=async e=>{const name=$('#gName').value.trim(),rules=$('#gRules').value.trim();if(!name||!rules){toast('نام بازی و قوانین را وارد کنید');return}const b=e.currentTarget;b.disabled=true;b.textContent='در حال ساخت...';
  try{const game=$('#gGame').value;const j=await aiJSON(AI_SYS,`Create a dedicated full-screen GAME INTRO block for a separate recording that the editor will cut into the episode. Game name: ${name}. Visual key: ${game}. Vibe: ${$('#gVibe').value}. Time/reward: ${$('#gMeta').value||'unknown'}. Unit: ${P.unit}. Raw rules from the producer:\n${rules}\n\nReturn exactly 3 segments with game="${game}": (1) type "intro" titled with the game name + a short subtitle, 2-3 emotional host lines that sell the challenge (suspense then hype); (2) type "rules" with clean short rules and lines: one opener + exactly one line per rule in the same order, emotion matching each rule's weight, last line hype; (3) type "countdown" titled "آماده‌اید؟". Brief can be minimal.`);
    const segs=(j.segments||[]).map(s=>Object.assign(s,{game}));const n=applySegments(segs,true);toast(`${fa(n)} مرحلهٔ معرفی و قوانین اضافه شد`);st.sel=P.segments.length-n;renderIntro()}catch(err){toast(err.message,5000)}finally{b.disabled=false;b.innerHTML='<i data-lucide="sparkles"></i>بساز و اضافه کن';icons(b)}};
$('#offGame').onclick=()=>{const name=$('#gName').value.trim()||'بازی جدید';const rules=$('#gRules').value.split('\n').map(x=>x.trim()).filter(Boolean);if(!rules.length){toast('قوانین را وارد کنید');return}const game=$('#gGame').value;
  applySegments([{type:'intro',game,title:name,subtitle:'چالش بعدی',lines:[{emotion:'suspense',text:'چالش بعدی...'},{emotion:'excited',text:name+'!'}]},{type:'rules',game,title:'قوانین '+name,rules,lines:[{emotion:'calm',text:'قوانین رو خوب گوش کنید.'},...rules.map((r,i)=>({emotion:i===rules.length-1?'excited':'calm',text:r}))]},{type:'countdown',title:'آماده‌اید؟'}],true);toast('معرفی و قوانین اضافه شد');renderIntro()};
/* voice page */
$('#voiceTable').addEventListener('click',e=>{const b=e.target.closest('[data-va]');if(!b)return;const tr=b.closest('tr');const ln=lineAt(+tr.dataset.si,+tr.dataset.li);if(!ln)return;b.dataset.va==='play'?previewLine(ln):genLine(ln,b)});
let genBusy=false;$('#genAll').onclick=async e=>{if(genBusy){genBusy=false;return}const todo=allLines().filter(x=>vstat(x.l)!=='ready'&&x.l.text.trim()&&['gemini','openai','piper','edge'].includes(spk(x.l.speaker).provider));if(!todo.length){toast('همهٔ صداهای قابل ساخت آماده‌اند');return}
  const b=e.currentTarget;genBusy=true;let done=0,fail=0,lastErr='';
  for(const x of todo){if(!genBusy)break;b.textContent=`در حال ساخت ${fa(done+1)} از ${fa(todo.length)} · برای توقف بزنید`;try{await synthLine(x.l)}catch(err){fail++;lastErr=err.message;console.warn(err);if(fail>=3&&done-fail<1){toast(lastErr,6000);break}}done++;renderVoice();await sleep(350)}
  genBusy=false;b.innerHTML='<i data-lucide="sparkles"></i>ساخت و نصب همهٔ صداهای ناقص';icons(b);toast(fail?`${fa(done-fail)} ساخته شد، ${fa(fail)} خطا: ${lastErr}`:'همهٔ صداها ساخته و روی دستگاه نصب شدند ✓',5000);refreshVoiceBits()};
$('#speakers').addEventListener('change',e=>{const f=e.target.dataset.spf;if(!f)return;const i=+e.target.closest('[data-sp]').dataset.sp;const sp=P.speakers[i];sp[f]=e.target.value;
  if(f==='provider'){sp.voice=sp.provider==='piper'?(S.piperVoice||'fa_IR-amir-medium'):(DEF_VOICE[sp.provider]||'')}save();renderVoice();renderROS()});
$('#speakers').addEventListener('input',e=>{if(e.target.dataset.spf==='name'){P.speakers[+e.target.closest('[data-sp]').dataset.sp].name=e.target.value;save()}});
$('#speakers').addEventListener('click',async e=>{const b=e.target.closest('[data-spa]');if(!b)return;const i=+b.closest('[data-sp]').dataset.sp;const sp=P.speakers[i];
  if(b.dataset.spa==='del'){P.segments.forEach(s=>s.lines.forEach(l=>{if(l.speaker===sp.id)l.speaker=P.speakers[i===0?1:0].id}));P.speakers.splice(i,1);save();renderVoice();return}
  const ln={id:'t',speaker:sp.id,emotion:'excited',text:'سلام به همه! آماده‌اید برای بزرگ‌ترین چالش امشب؟',direction:''};b.disabled=true;const old=b.innerHTML;b.textContent='در حال ساخت نمونه...';
  try{await AE.resume();let blob;if(sp.provider==='gemini')blob=await ttsGemini(ln,sp.voice);else if(sp.provider==='openai')blob=await ttsOpenAI(ln,sp.voice);else if(sp.provider==='piper')blob=await Piper.speak(ttsText(ln),sp.voice);else if(sp.provider==='edge')blob=await ttsEdge(ln,sp.voice);else{deviceSpeak(ln);return}
    AE.play(await AE.ctx.decodeAudioData(await blob.arrayBuffer()))}catch(err){toast(err.message,5000)}finally{b.disabled=false;b.innerHTML=old}});
$('#addSpeaker').onclick=()=>{P.speakers.push({id:uid(),name:'گوینده '+fa(P.speakers.length+1),provider:P.speakers[0].provider,voice:'Zephyr'});save();renderVoice()};
$('#persistBtn').onclick=async()=>{try{const ok=await navigator.storage.persist();toast(ok?'ذخیرهٔ دائمی فعال شد؛ مرورگر صداها را پاک نمی‌کند':'مرورگر اجازه نداد؛ اپ را نصب کنید (افزودن به صفحهٔ اصلی) و دوباره بزنید',4500)}catch(e){toast('این مرورگر پشتیبانی نمی‌کند')}storageInfo();renderPreflight()};
async function voicePackObj(){const out={format:'dadashmode-voicepack/3',created:Date.now(),items:{}};for(const x of allLines()){const r=lineRec(x.l);if(r&&!out.items[r.key])out.items[r.key]=Object.assign({},r,{blob:undefined,mime:r.blob.type,data:await blobToData(r.blob)})}return out}
async function installPackObj(j){let n=0;for(const[key,r]of Object.entries(j.items||j.lines||{})){if(!r.data)continue;const rec=Object.assign({},r,{key,blob:await dataToBlob(r.data)});delete rec.data;await DB.put('audio',key,rec);AUD.set(key,rec);BUF.delete(key);n++}return n}
$('#exportVoice').onclick=async()=>{download(new Blob([JSON.stringify(await voicePackObj())],{type:'application/json'}),safeName(P.name)+' - voices.json');toast('بستهٔ صدا ذخیره شد')};
$('#importVoice').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const n=await installPackObj(JSON.parse(await f.text()));toast(fa(n)+' صدا نصب شد');refreshVoiceBits()}catch(err){toast('فایل معتبر نیست')}e.target.value=''};
$('#exportWavs').onclick=async()=>{const ls=allLines().filter(x=>lineRec(x.l));if(!ls.length){toast('صدایی نصب نشده');return}
  if(window.showDirectoryPicker){try{const h=await showDirectoryPicker({mode:'readwrite'});let n=0;for(const x of ls){const r=lineRec(x.l);const ext=/wav/.test(r.blob.type)?'wav':/mpeg|mp3/.test(r.blob.type)?'mp3':/webm/.test(r.blob.type)?'webm':'wav';const nm=safeName(`S${String(x.si+1).padStart(2,'0')}-L${String(x.li+1).padStart(2,'0')} ${x.l.text.slice(0,40)}`)+'.'+ext;const fh=await h.getFileHandle(nm,{create:true});const w=await fh.createWritable();await w.write(r.blob);await w.close();n++}toast(fa(n)+' فایل برای تدوین ذخیره شد')}catch(e){}}
  else{for(const x of ls.slice(0,40)){const r=lineRec(x.l);download(r.blob,safeName(`S${x.si+1}-L${x.li+1} ${x.l.text.slice(0,30)}`)+'.wav');await sleep(250)}}};
$('#piperInstall').onclick=async e=>{const b=e.currentTarget;b.disabled=true;$('#piperInfo').textContent='در حال بارگذاری موتور...';try{const vs=await Piper.voices();const id=vs.includes('fa_IR-amir-medium')?'fa_IR-amir-medium':vs[0];if(!id)throw new Error('صدای فارسی در فهرست موتور پیدا نشد');
  await Piper.install(id,p=>$('#piperInfo').textContent='دانلود '+fa(Math.round(p*100))+'٪');S.piperVoice=id;saveS();$('#piperInfo').textContent='نصب شد: '+id+' · برای استفاده، موتور یک گوینده را «اضطراری» کنید';}catch(err){$('#piperInfo').textContent='نصب نشد: '+err.message}finally{b.disabled=false}};
/* look page */
$('#themes').onclick=e=>{const b=e.target.closest('[data-th]');if(!b)return;P.theme=Object.assign({font:P.theme.font},THEMES[+b.dataset.th]);save();renderLook()};
$('#colors').addEventListener('input',e=>{const k=e.target.dataset.col;if(!k)return;if(e.target.value.toLowerCase()==='#ff00ff'){toast('این رنگ برای کروما رزرو است');return}P.theme[k]=e.target.value;P.theme.name='سفارشی';save();$$('.theme-sw').forEach(x=>x.setAttribute('aria-pressed','false'))});
$('#lyFont').onchange=async e=>{P.theme.font=e.target.value;save();try{await document.fonts.load(F(40),'سلام')}catch(err){}};
$('#lyScore').onchange=e=>{P.layout.score=e.target.value;save()};$('#lyTimer').onchange=e=>{P.layout.timer=e.target.value;save()};
$('#lySub').oninput=e=>{P.layout.sub=+e.target.value;$('#lySubV').textContent=fa(e.target.value);save()};$('#lyGreen').onchange=e=>{P.layout.green=e.target.checked;save()};$('#lyGuides').onchange=e=>{P.layout.guides=e.target.checked;save();$('#guides').classList.toggle('hidden',!P.layout.guides)};
$('#unitIn').oninput=e=>{P.unit=e.target.value||'ثانیه';save()};$('#startIn').oninput=e=>{P.startBank=Math.max(0,+e.target.value||0);save()};
$('#playersEdit').addEventListener('input',e=>{const f=e.target.dataset.pf;if(!f)return;const p=P.players[+e.target.closest('[data-pe]').dataset.pe];if(f==='color'&&e.target.value.toLowerCase()==='#ff00ff')return;p[f]=e.target.value;save()});
$('#playersEdit').addEventListener('click',e=>{const b=e.target.closest('[data-pdel]');if(!b)return;if(P.players.length<=1){toast('حداقل یک بازیکن لازم است');return}P.players.splice(+b.dataset.pdel,1);save();renderLook()});
$('#addPlayer').onclick=()=>{if(P.players.length>=6){toast('حداکثر ۶ بازیکن');return}const i=P.players.length;P.players.push({id:uid(),name:'بازیکن '+fa(i+1),color:PLAYER_COLS[i%PLAYER_COLS.length],symbol:['▲','●','■','◆','★','✚'][i],key:['a','l','s','k','d','j'][i]});save();renderLook()};
async function setLogoCut(global){if(!P.logo)return;P.logo.tol=+$('#logoTol').value;P.logo.cut=await cutLogo(P.logo.orig,P.logo.tol,global);save();loadLogoImg();renderLook()}
$('#logoFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const orig=await blobToData(f);P.logo={orig,cut:null,tol:42};toast('در حال تحلیل و جداسازی پس‌زمینه...');P.logo.cut=await cutLogo(orig,42,false);save();loadLogoImg();renderLook();e.target.value='';
  try{const pal=await logoPalette(P.logo.cut);if(pal.length){$('#logoPal').innerHTML='<span class="muted">رنگ‌های لوگو:</span>'+pal.map(c=>`<button class="btn sm" data-pal="${c}"><span style="width:16px;height:16px;border-radius:50%;background:${c};display:inline-block"></span>تم با این رنگ</button>`).join('')}}catch(err){}};
$('#logoPal').addEventListener('click',e=>{const b=e.target.closest('[data-pal]');if(!b)return;const c=b.dataset.pal;P.theme=Object.assign({},P.theme,{name:'از لوگو',accent:c,bg2:mix(c,'#000000',.62),bg1:mix(c,'#000000',.9),shade:mix(c,'#000000',.55)});save();renderLook();toast('تم از رنگ لوگو ساخته شد')});
$('#logoTol').oninput=e=>{$('#tolV').textContent=fa(e.target.value)};$('#logoAuto').onclick=()=>setLogoCut(false);$('#logoGlobal').onclick=()=>setLogoCut(true);
$('#logoKeep').onclick=()=>{if(!P.logo)return;P.logo.cut=null;save();loadLogoImg();renderLook()};$('#logoDel').onclick=()=>{P.logo=null;save();loadLogoImg();renderLook()};
/* projects */
async function openProject(p){stopAll();P=migrate(p);st.sel=0;st.disp={};st.fx=[];await DB.put('projects',P.id,P);localStorage.setItem('dm3-last',P.id);loadLogoImg();renderControl();renderProjects()}
function cloneEpisode(src){const p=JSON.parse(JSON.stringify(src));p.id=uid();p.created=Date.now();p.updated=Date.now();p.segments.forEach(s=>{s.id=uid();s.lines.forEach(l=>l.id=uid())});p.game=freshGame();return p}
async function importEpisodeJSON(j){if(j.audio||j.voices){await installPackObj(j.voices||{items:j.audio})}const src=j.project||j.episode||j;if(!src.segments)throw new Error('bad');await openProject(cloneEpisode(migrate(src)));toast('قسمت وارد شد');showView('control')}
$('#newTpl').onclick=async()=>{await openProject(migrate(defaultEpisode()));toast('قسمت جدید از قالب بانک زمان ساخته شد');showView('control')};
$('#newBlank').onclick=async()=>{const p=defaultEpisode();p.name='قسمت جدید';p.brief=null;p.segments=[mkSeg({type:'title',title:'داداش‌مود',subtitle:'قسمت جدید'})];await openProject(migrate(p));showView('script')};
$('#projList').addEventListener('click',async e=>{const b=e.target.closest('[data-pa]');if(!b)return;const id=b.closest('[data-pid]').dataset.pid;const p=await DB.get('projects',id);const a=b.dataset.pa;
  if(a==='open'){await openProject(p);showView('control')}
  else if(a==='dup'){const c=cloneEpisode(p);c.name=p.name+' · نسخهٔ جدید';await DB.put('projects',c.id,c);toast('کپی ساخته شد (صداهای یکسان خودکار دوباره استفاده می‌شوند)؛ سناریوی ویدیوی بعدی را به آن بدهید',4500);renderProjects()}
  else if(a==='exp'){const prev=P;P=migrate(JSON.parse(JSON.stringify(p)));const voices=await voicePackObj();P=prev;const out={format:'dadashmode-project/3',project:p,voices};download(new Blob([JSON.stringify(out)],{type:'application/json'}),safeName(p.name)+'.dadashmode.json')}
  else if(a==='del'){if(p.id===P.id){toast('قسمت باز را نمی‌شود حذف کرد');return}if(b.dataset.armed!=='1'){b.dataset.armed='1';b.textContent='مطمئنید؟';setTimeout(()=>{b.dataset.armed='';b.textContent='حذف'},2500);return}await DB.del('projects',id);renderProjects()}});
$('#importProj').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importEpisodeJSON(JSON.parse(await f.text()))}catch(err){console.error(err);toast('فایل قسمت معتبر نیست')}e.target.value=''};
$('#takes').addEventListener('click',async e=>{const b=e.target.closest('[data-ta]');if(!b)return;const row=b.closest('[data-tid]');const t=await DB.get('takes',row.dataset.tid);const a=b.dataset.ta;
  if(a==='view'){let v=row.querySelector('video');if(!v){v=document.createElement('video');v.controls=true;v.playsInline=true;v.src=URL.createObjectURL(t.blob);row.firstElementChild.appendChild(v)}v.play()}
  else if(a==='dl')download(t.blob,t.name);else if(a==='srt')download(new Blob([t.srt],{type:'text/plain;charset=utf-8'}),t.name.replace(/\.\w+$/,'.srt'));
  else if(a==='share'){const file=new File([t.blob],t.name,{type:t.blob.type});if(navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:t.name})}catch(err){}}else{download(t.blob,t.name);toast('اشتراک مستقیم پشتیبانی نشد؛ فایل دانلود شد تا در فضای ابری آپلود کنید',4500)}}
  else if(a==='del'){if(b.dataset.armed!=='1'){b.dataset.armed='1';b.textContent='مطمئنید؟';setTimeout(()=>{b.dataset.armed='';b.textContent='حذف'},2500);return}await DB.del('takes',t.id);renderTakes()}});
/* settings */
const bindS=(sel,key,kind)=>$(sel).addEventListener('change',e=>{S[key]=kind==='bool'?e.target.checked:kind==='num'?+e.target.value:e.target.value.trim();saveS();if(key==='quality')setQuality();if(AE.ctx){AE.sfx.gain.value=S.sfxVol;AE.voice.gain.value=S.voiceVol}if(key==='normalize')BUF.clear();renderSettings();renderPreflight()});
bindS('#sProv','aiProvider');bindS('#sGKey','geminiKey');bindS('#sGChat','geminiChat');bindS('#sGTts','geminiTts');bindS('#sOKey','openaiKey');bindS('#sOBase','openaiBase');bindS('#sOChat','openaiChat');bindS('#sOTts','openaiTts');
bindS('#sQual','quality');bindS('#sFps','fps','num');bindS('#sAutoDl','autoDl','bool');bindS('#sDevTts','devTts','bool');bindS('#sNorm','normalize','bool');bindS('#sBed','musicBed','bool');bindS('#sWake','wake','bool');bindS('#sSfx','sfxVol','num');bindS('#sVoice','voiceVol','num');
$$('[data-show]').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.show);i.type=i.type==='password'?'text':'password'});
$('#pickFolder').onclick=pickFolder;
$('#sTest').onclick=async()=>{['geminiKey:#sGKey','openaiKey:#sOKey','openaiBase:#sOBase'].forEach(x=>{const[k,s]=x.split(':');S[k]=$(s).value.trim()});saveS();$('#sTestOut').textContent='در حال تست...';
  try{const j=await aiJSON('Reply with JSON {"ok":true,"msg":"<a short friendly Persian greeting>"}','test');$('#sTestOut').textContent='اتصال متن برقرار است ✓ '+(j.msg||'')}catch(e){$('#sTestOut').textContent=e.message}};
function renderNet(){const on=navigator.onLine;const el=$('#net');el.textContent=on?'آنلاین':'آفلاین · نمایش ادامه دارد';el.className='net '+(on?'on':'off')}
window.addEventListener('online',renderNet);window.addEventListener('offline',renderNet);

/* ---------------- boot ---------------- */
async function boot(){icons();renderSfx();renderNet();await DB.open();for(const r of await DB.all('audio'))AUD.set(r.key,r);
  const last=localStorage.getItem('dm3-last');let p=last&&await DB.get('projects',last);if(!p){const all=await DB.all('projects');p=all[0]}
  if(!p){p=migrate(defaultEpisode());await DB.put('projects',p.id,p)}P=migrate(p);localStorage.setItem('dm3-last',P.id);
  setQuality();loadLogoImg();renderControl();requestAnimationFrame(frame);
  try{await Promise.all(['900 40px Vazirmatn','800 40px Vazirmatn','40px Lalezar','900 40px Estedad','900 40px "Noto Kufi Arabic"','700 40px Marhey'].map(f=>document.fonts.load(f,'سلام ۱۲۳')));st.fonts=document.fonts.check('40px Lalezar','سلام')}catch(e){st.fonts=false}
  const n=await loadInstalledPack();if(n){toast(fa(n)+' صدا از بستهٔ نصبی کنار اپ نصب شد');refreshVoiceBits()}renderPreflight();
  if(window.speechSynthesis)speechSynthesis.onvoiceschanged=()=>{if(!$('#view-voice').classList.contains('hidden'))renderVoice()};
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&st.rec)toast('حین ضبط این تب را باز نگه دارید')});
  if('serviceWorker' in navigator&&location.protocol.startsWith('http')){try{await navigator.serviceWorker.register('sw.js');navigator.serviceWorker.addEventListener('controllerchange',()=>renderPreflight())}catch(e){console.warn(e)}}
}
